In [2]:
# For Visualization (run this cell)
!pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\acer\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\acer\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\acer\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\acer\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\acer\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\acer\anaconda3\lib\site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\acer\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\acer\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\acer\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\acer\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\acer\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

**Dataset links:** https://drive.google.com/drive/folders/1w5hEC-qa5HZJiTXY8rbu1eisYqA51WJu?usp=sharing

In [3]:
import pandas as pd

In [4]:
# Read datasets
election_df = pd.read_csv("election_data.csv")
district_df = pd.read_csv("district_data.csv")
province_df = pd.read_csv("province_data.csv")

In [24]:
# Check top 5 rows of election dataset

# elec =pd.read_csv("election_data.csv")
# elec
elec.head(5)

,candidate_id,district_id,const_name,candidate_name,age,gender,party,votes
0,339300,4,Jhapa-5,Dharmraj Guragain,43,male,People First Party,34
1,339301,71,Kailali-5,Pyare Lal Rana,61,male,Independent,1755
2,339302,31,Makwanpur-1,Bidya Shrestha Maharjan,49,female,Shram Sanskriti Party,1024
3,339303,33,Bara-3,Chandra Prakash Suwedi,59,male,Independent,9
4,339304,35,Chitwan-3,Indra Maya Paudel,58,female,Independent,398

In [22]:
# Check the information of election dataset
elec.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3406 entries, 0 to 3405
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   candidate_id    3406 non-null   int64
 1   district_id     3406 non-null   int64
 2   const_name      3406 non-null   object
 3   candidate_name  3406 non-null   object
 4   age             3406 non-null   int64
 5   gender          3406 non-null   object
 6   party           3406 non-null   object
 7   votes           3406 non-null   int64
dtypes: int64(4), object(4)
memory usage: 213.0+ KB

In [25]:
# Statistical summary of election dataset
elec.describe()

        candidate_id  district_id          age         votes
count    3406.000000  3406.000000  3406.000000   3406.000000
mean   341043.324427    32.786553    46.959777   3091.354668
std      1009.146462    19.164638    11.276963   7793.436225
min    339300.000000     1.000000    25.000000      0.000000
25%    340169.250000    20.000000    39.000000     17.000000
50%    341039.500000    28.000000    47.000000     87.000000
75%    341917.750000    46.000000    55.000000    964.500000
max    342797.000000    77.000000    88.000000  68348.000000

In [28]:
# Find if there any null values in dataset
elec.isna().sum()

candidate_id      0
district_id       0
const_name        0
candidate_name    0
age               0
gender            0
party             0
votes             0
dtype: int64

In [40]:
columns=["candidate_name","const_name","votes"]
elec[["candidate_name","const_name","votes"]]

                candidate_name   const_name  votes
0            Dharmraj Guragain      Jhapa-5     34
1               Pyare Lal Rana    Kailali-5   1755
2      Bidya Shrestha Maharjan  Makwanpur-1   1024
3       Chandra Prakash Suwedi       Bara-3      9
4            Indra Maya Paudel    Chitwan-3    398
...                        ...          ...    ...
3401   Nitima Bhandari (Karki)    Sarlahi-1  44181
3402          Ram Dular Mahato    Sarlahi-1     10
3403       Kishor Kumar Biswas    Sunsari-3    225
3404  Deepak Kumar Gauri Magar      Banke-3   4015
3405        Rabindra Chaudhary    Saptari-1   1626

[3406 rows x 3 columns]

#### 1. Find total number of `male` and `female` candidates.

In [46]:
# Code here
# If possible, plot a bar chart
elec["gender"].value_counts()

gender
male      3017
female     388
other        1
Name: count, dtype: int64

#### 2. Total number of `GenZ candidates` registered for the election.

In [50]:
# Code here
# Hint: GenZ -> age between 14 to 29
condition=(elec["age"]>=14) & (elec["age"]<=29)
# elec[condition].shape
len(elec[condition])

201

#### 3. Who are the `top 3 candidates` who won with the highest individual vote counts?

In [56]:
# Code here
elec.sort_values("votes", ascending=False).head(3)

,candidate_id,district_id,const_name,candidate_name,age,gender,party,votes
348,339653,4,Jhapa-5,Balendra Shah,36,male,Rastriya Swatantra Party,68348
77,339380,4,Jhapa-2,Indira Rana Magar,55,female,Rastriya Swatantra Party,60110
1806,341145,35,Chitwan-3,Sobita Gautam,30,female,Rastriya Swatantra Party,59277

#### 4. Which `10 political parties` have the highest number of candidates?

In [59]:
# Code here
elec["party"].value_counts()[1:11]

party
Nepali Congress                      165
Communist Party of Nepal             164
Rastriya Swatantra Party             164
CPN (Unified Marxist-Leninist)       164
Rastriya Prajatantra Party           163
Communist Party of Nepal (Maoist)    130
Nepal Majdoor Kisan Party            120
Mongol National Organisation         113
Shram Sanskriti Party                109
Ujyalo Nepal Party                   105
Name: count, dtype: int64

#### 5. For every `constituency`, find the candidate who received the highest votes and assign to variable `winner_df`

In [78]:
# Code here

i= election_df.groupby("const_name")["votes"].idxmax()
winner_df=election_df.iloc[i]
winner_df

,candidate_id,district_id,const_name,candidate_name,age,gender,party,votes
2306,341661,68,Achham-1,Bharat Kumar Swar,70,male,Nepali Congress,10759
1281,340611,68,Achham-2,Yagya Bahadur Bogati,50,male,CPN (Unified Marxist-Leninist),9518
335,339640,44,Arghakhanchi-1,Hari Prasad Bhusal,37,male,Rastriya Swatantra Party,35023
645,339959,50,Baglung-1,Sushil Khadka,39,male,Rastriya Swatantra Party,20927
2672,342039,50,Baglung-2,Som Sharma,34,male,Rastriya Swatantra Party,12647
...,...,...,...,...,...,...,...,...
1785,341124,40,Tanahun-2,Shreeram Neupane,56,male,Rastriya Swatantra Party,32687
620,339933,1,Taplejung-1,Khitiz Thebe,38,male,CPN (Unified Marxist-Leninist),13962
1282,340612,6,Terhathum-1,Santosh Subba,48,male,Nepali Congress,11561
2137,341485,14,Udayapur-1,Paras Mani Gelal,40,male,Rastriya Swatantra Party,30590
2319,341674,14,Udayapur-2,Surya Bahadur Tamang,41,male,Rastriya Swatantra Party,14802

In [79]:
# Calculate the percentage of female winners
winner_df["gender"].value_counts()["female"]/len(winner_df)*100

np.float64(8.484848484848486)

#### 6. Compute how many constituency each party won.

In [80]:
# Code here 
winner_df["party"].value_counts()

party
Rastriya Swatantra Party          125
Nepali Congress                    18
CPN (Unified Marxist-Leninist)      9
Communist Party of Nepal            8
Shram Sanskriti Party               3
Rastriya Prajatantra Party          1
Independent                         1
Name: count, dtype: int64

#### 7. Which province had the highest total votes casted?

In [92]:
# Code here
temp_df=elec.merge(district_df,on ="district_id").merge(province_df,on="province_id")
# winner_df["district_id"].value_counts("votes")
# winner_df.head(5)
temp_df.groupby("province_name")["votes"].sum().sort_values(ascending=False)

province_name
Madhesh          2158414
Bagmati          2140729
Koshi            1953372
Lumbini          1917649
Gandaki           992578
Sudurpashchim     822944
Karnali           543468
Name: votes, dtype: int64

#### 8. For all constituencies, find the `winner` and `first runner-up` and assign that output to variable `top_2`

In [ ]:
# Code here
# hint-> maker use of nlargest()  and reset-index()

#### 9. Compute the `margin` between `winner` and `first runner-up` for each constituency.

In [ ]:
# Code here
# hint- apply() methods

#### 10. Identifies the top 10 most competitive constituency (lowest margins).

In [ ]:
# Code here
# hint sort_values()

**_Analyze this data further using your own creativity! Happy Coding🎉🎉_**